export const categoriesData = [
    "Medicine & Public Health",
    "Life Sciences",
    "Chemistry",
    "Physics",
    "Biomedicine",
    "Engineering",
    "Materials Science",
    "Mathematics",
    "Earth Sciences",
    "Computer Science",
    "Environment",
    "Psychology",
    "Pharmacy",
    "Social Sciences",
    "Science, Humanities and Social Sciences, multidisciplinary",
    "Economics",
    "Business and Management",
    "Philosophy",
    "Education",
    "Dentistry",
    "Law",
    "Statistics",
    "Political Science and International Relations",
    "Energy",
    "Linguistics",
    "Geography",
    "Finance",
    "Criminology and Criminal Justice",
    "Literature",
    "Cultural and Media Studies",
    "History",
    "Architecture / Design",
    "Medicine",
    "Religious Studies",
    "Biomedical Sciences",
    "Materials",
    "Earth Sciences & Geography",
    "Material Science",
    "Environmental Sciences",
    "Astronomy",
    "Business & Management",
    "Education & Language",
    "Earth Sciences and Geography"
]
